FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y \
        git \
        vim \
        cmake \
        build-essential \
        libgtest-dev \
        libcurl4-openssl-dev \
        clang-format-14

RUN bash
